### PR TITLE
Did Some Stuff ( lol )

### PR DESCRIPTION
**Pull request by mrhut10**
* converted to statefull function - can never remember how to use classes so i avoid, sorry if you preferred it as a class?
* added State - so we could lift the selectedSlide managed by a child up to a this parent element
* found a method that had current slide as a prop in it
     // note you've already using some methods that could get a prop of currently slide, however it was only updated just before it would change. i.e. clicking nextSlide or previousSlide
* added logic within your map to to add a className if it is in the middle, which i can't believe it worked first go. #win

have you used modula division before??

a basic description of the logic is
(SlideSelected + 1)           // moves it to the middle slide
(SlideSelected + 1) % edges.length     // this modular division will handle cases where you reach the end of the array and go back to the beginning for you.

example of logic below will return return 0;
const [selectedSlide, totalSlides] = [15, 16];
()=>{
  return (selectedSlide + 1) % TotalSlides
}

sorry if i'm way over explaining this

### CODE REVIEW

**Comment by mrhut10** [comment]
@lukebennett88 

BTW looks like a easy library to use for the carousel i think i could use it to display more than one image on product images on futures fine furniture.

also feel free to change my silly classNames i'm adding to the images
and also I'm hopping this is actually what you needed, what you where asking was going off my head a little.

you could use a didComponentMount to select a element outside of reacts control, however by using a little state and lifting information back out of the library to your parent element that complexity can be avoided.

**Comment by lukebennett88** [comment]
This is perfect @mrhut10!!!!
Just need to get the CSS to do what it's meant to do and I'll merge it.
BTW, I see you're all in on Hooks at the moment.

**Comment by mrhut10** [comment]
Felt like I had a super power last night, fluked it and solved it on first attempt with the Modula division. Couldn't believe it.

And yeah because there's be such a long time sence I've used classes and the old state it seems so unfimilar. I find it so much easier to write it functionally with hooks.

So yep the class method is a weakness for me now, a struggle

**Comment by mrhut10** [comment]
Putting this functionality of addressing the middle element separately would be a good pr back to the original author of the library btw.

**Comment by mrhut10** [comment]
How's the styling with it going?

**Comment by lukebennett88** [comment]
Took a while to work out the best way to do it. Have some issues with `overflow: hidden` cutting images off if I use a transform to scale things up, and `transform: scale(0.75)` causes a gap, `transform: scaleY(0.75)` causes the images to warp.
Very fiddly.
I've been messing around with the different props available and with a bit of trial and error I think I've got something to work.
For some reason if I have `slidesToShow` set to 3, when I have `transitionMode="scroll3d"` set, I get 5 slides shown. If I set it to 2, I get 3 images on the screen ¯\_(ツ)_/¯
However adding these props seems to break your math, but when I looked at the source, there is now a new class of `slide-current` on the middle slide 🤦‍♂

**Comment by mrhut10** [comment]
Oh interesting,
The trouble with slide current, is that it's the left most photo and not the middle. I looked at that also.

The visual problem your having i can think of a way that would help. But you would be better at CSS to address this. Can I call you to describe?

**Pull request merged**
